config/routes.rb
Store::Application.routes.draw do
  root to: 'orders#index'
  resources :orders
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order

  def full_price
    unit_price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items

  def total_price
    # convert to array so it doesn't try to do sum on database directly
    line_items.to_a.sum(&:full_price)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        pdf = OrderPdf.new(@order, view_context)
        send_data pdf.render, filename: "order_#{@order.order_number}.pdf",
                              type: "application/pdf",
                              disposition: "inline"
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/orders/index.html.erb
<h1>Orders</h1>
<ul>
<% @orders.each do |order| %>
  <li><%= link_to "Order \##{order.order_number}", order %></li>
<% end %>
</ul>

app/views/orders/show.html.erb
<h1>Order #<%= @order.order_number %></h1>

<table id="line_items">
  <tr>
    <th>Product</th>
    <th>Qty</th>
    <th class="price">Unit Price</th>
    <th class="price">Full Price</th>
  </tr>
  <% @order.line_items.each do |line_item| %>
    <tr class="<%= cycle :odd, :even %>">
      <td><%= line_item.name %></td>
      <td class="qty"><%= line_item.quantity %></td>
      <td class="price"><%= number_to_currency(line_item.unit_price) %></td>
      <td class="price"><%= number_to_currency(line_item.full_price) %></td>
    </tr>
  <% end %>
  <tr>
    <td class="total price" colspan="4">
      Total: <%= number_to_currency @order.total_price %>
    </td>
  </tr>
</table>

<p><%= link_to "Printable Receipt (PDF)", order_path(@order, format: "pdf") %></p>